
[Interface]
PrivateKey = O01FobOgviA6Vy/j6jGjcR8FaCJLeha47nq8KO9SsB8=
Address = fdaa:c:f89:a7b:339:0:a:702/120
DNS = fdaa:c:f89::3

[Peer]
PublicKey = e3VEeKrNA9d9tLq9V1Nr7F4hNgCRcQEB8dcJ93JJjGY=
AllowedIPs = fdaa:c:f89::/48
Endpoint = bom1.gateway.6pn.dev:51820
PersistentKeepalive = 15

