# fly.toml app configuration file generated for automa-web-core-seleniumgrid-hub on 2025-08-22T14:12:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'automa-web-core-seleniumgrid-hub'
primary_region = 'jnb'

[build]
image = 'selenium/hub:latest'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
