# fly.toml app configuration file generated for automa-web-core-seleniumgrid-node on 2025-08-25T06:51:51-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'automa-web-core-seleniumgrid-node'
primary_region = 'jnb'

[build]
image = 'selenium/node-chrome:latest'

[env]
SE_EVENT_BUS_HOST = 'automa-web-core-seleniumgrid-hub.internal'

[[vm]]
memory = '2gb'
cpu_kind = 'performance'
cpus = 1
