name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: blacksmith-4vcpu-ubuntu-2404
    concurrency: deploy-group
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.1"

      - name: Get Cache
        uses: useblacksmith/cache@v5
        id: autoscaler-build
        with:
          key: deploy-cache-${{ hashFiles('SeleniumGridNodeMachineAutoscaler/Package.resolved') }}
          path: SeleniumGridNodeMachineAutoscaler/.build

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy App
        run: |
          echo "GH_SSH_AUTHENTICATION_TOKEN: ${{ secrets.GH_SSH_AUTHENTICATION_TOKEN }}"
          cd ./SeleniumGridNodeMachineAutoscaler && npm run deploy -- ./SeleniumGridNodeMachineAutoscaler/ --config=./infra/autoscaler.toml --build-secret GITHUB_SSH_AUTHENTICATION_TOKEN=${{ secrets.GH_SSH_AUTHENTICATION_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
